<?php if ($block->isBlockEnabled()) :
    $productId = $block->getFeaturedProductId();
    $product = $block->loadProductById($productId);
    if ($product) :
?>
    <div class="product-featured">
        <h2>Produto em Destaque</h2>
        <div>
            <img src="<?php echo $block->getImageUrl($product); ?>" alt="<?php echo $product->getName(); ?>">
            <p><?php echo $product->getName(); ?></p>
            <p>Valor <?php echo $product->getPrice(); ?></p>
        </div>
    </div>
<?php endif;
    endif; ?>